#Note: yaml doesn't support tab, use spaces instead

Env: dev
Name: dev.configs
ID:  node1

Genesis:
  Nonce: 1337

MiningSet:
  Enabled: true

RpcSet:
  Enabled: true
  Port: 3000

Storage:
  type: 1         #1: LEVEL_DB
  DBName: "badcoin"
  Collections:
    Blocks: "blocks"
    UTXO: "chainstate"
    TXsMemPool: "txmempool"
    BlockIndex: "blockindex"
    Stats:      "stats"